# Generated by Django 3.2.5 on 2021-10-27 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('ident', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('idp', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('pet', models.TextField(max_length=40)),
                ('birth_date', models.DateTimeField(null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('height', models.TextField(max_length=40)),
                ('weight', models.TextField(max_length=40)),
                ('pet_type', models.TextField(max_length=40)),
                ('medical_condition', models.TextField(max_length=4000)),
                ('pet_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
